name: Build image

on:
  schedule:
    - cron:  '14 3 * * *'
    
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu20.04", "ubuntu22.04", "centos7"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildWithDocker.html
      - 
        name: Checkout OpenROAD
        run: git clone --depth=1 --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
      - 
        name: Build OpenROAD
        run: |
          cd OpenROAD-flow-scripts
          ./build_openroad.sh --os=${{ matrix.os }}
      - 
        name: Tag image
        run: docker tag openroad/flow-${{ matrix.os }}-builder killruana/openroad:${{ matrix.os }}
      - 
        name: Push image
        run: docker push killruana/openroad:${{ matrix.os }}-latest
